# Naive bayes - socail network data

In [50]:
import numpy as np 
import pandas as pd

In [51]:
df = pd.read_csv("Social_Network_Ads .csv",
                 usecols = ['Age' , 'EstimatedSalary' , 'Purchased'])

In [52]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [53]:
x = df.drop(columns = ['Purchased'])
y = df['Purchased']

In [54]:
from sklearn.model_selection import train_test_split 

In [99]:
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,
                                                    random_state=42)

In [100]:
from sklearn.preprocessing import StandardScaler

In [101]:
sc = StandardScaler()

In [102]:
x_train_new = sc.fit_transform(x_train)

In [103]:
x_test_new = sc.transform(x_test)

In [104]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [105]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [106]:
y_pred = classifier.predict(x_test_new) 

In [107]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [108]:
from sklearn.metrics import confusion_matrix

In [109]:
cn = confusion_matrix(y_test,y_pred)

In [110]:
cn

array([[50,  2],
       [ 3, 25]])

In [111]:
from sklearn.metrics import accuracy_score

In [112]:
accuracy_score(y_test , y_pred)

0.9375

In [113]:
from sklearn.metrics import precision_score

In [114]:
precision_score(y_test , y_pred)

0.9259259259259259

# naive bayes - covid toy data

In [117]:
df = pd.read_csv("covid_toy.csv")
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [119]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [120]:
from sklearn.impute import SimpleImputer

In [121]:
si = SimpleImputer()

In [122]:
df['fever']= si.fit_transform(df[['fever']])

In [123]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [124]:
from sklearn.preprocessing import LabelEncoder

In [125]:
lb = LabelEncoder()

In [126]:
df['gender']= lb.fit_transform(df['gender'])
df['cough']= lb.fit_transform(df['cough'])
df['city']= lb.fit_transform(df['city'])
df['has_covid']= lb.fit_transform(df['has_covid'])

In [127]:
df.head(2)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1

In [128]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [129]:
from sklearn.model_selection import train_test_split 

In [130]:
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,
                                                    random_state=23)

In [131]:
from sklearn.preprocessing import StandardScaler

In [132]:
sc = StandardScaler()

In [133]:
x_train_new = sc.fit_transform(x_train)

In [134]:
x_test_new = sc.transform(x_test)

In [135]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()

In [136]:
gn.fit(x_train_new,y_train)

GaussianNB()

In [137]:
y_pred = gn.predict(x_test_new) 

In [138]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [139]:
from sklearn.metrics import confusion_matrix

In [140]:
cn = confusion_matrix(y_test,y_pred) 

In [141]:
cn

array([[7, 6],
       [3, 4]])

In [143]:
from sklearn.metrics import accuracy_score

In [144]:
accuracy_score(y_test , y_pred)

0.55

In [142]:
from sklearn.metrics import precision_score

In [145]:
precision_score(y_test , y_pred)

0.4